import uuid
import pytest
from httpx import AsyncClient, ASGITransport

from app.main import app
from app.core.dependencies import get_ai_service
from app.services.ai_service import AIService, AIServiceError, ChatTurn


class FakeAIService(AIService):
    def __init__(self, reply: str = "Test assistant reply generated by the fake AI service."):
        self.reply = reply
        self.calls = 0
        self.fail_next = False

    async def generate_reply(self, *, system_prompt: str, history: list[ChatTurn]) -> str:
        self.calls += 1
        if self.fail_next:
            self.fail_next = False
            raise AIServiceError("Simulated AI provider failure.", status_code=502)
        if not history:
            raise AIServiceError("Empty history", status_code=400)
        return self.reply


@pytest.fixture
def anyio_backend():
    return "asyncio"


@pytest.fixture
def fake_ai():
    service = FakeAIService()
    app.dependency_overrides[get_ai_service] = lambda: service
    yield service
    app.dependency_overrides.pop(get_ai_service, None)


async def _register_and_onboard(client: AsyncClient, email: str, password: str, name: str) -> str:
    reg = await client.post(
        "/api/v1/auth/register",
        json={"email": email, "password": password},
    )
    assert reg.status_code == 201
    token = reg.json()["access_token"]
    headers = {"Authorization": f"Bearer {token}"}
    profile = await client.post(
        "/api/v1/profile",
        headers=headers,
        json={
            "display_name": name,
            "timezone": "UTC",
            "wellness_goals": ["Sleep Better"],
            "activity_level": "moderate",
            "onboarding_completed": True,
        },
    )
    assert profile.status_code == 201
    return token


@pytest.mark.asyncio
async def test_conversations_require_authentication(fake_ai):
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as client:
        unauth = await client.get("/api/v1/conversations")
        assert unauth.status_code == 401

        invalid = await client.get(
            "/api/v1/conversations",
            headers={"Authorization": "Bearer not-a-real-jwt"},
        )
        assert invalid.status_code == 401


@pytest.mark.asyncio
async def test_conversation_crud_and_message_persistence(fake_ai):
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as client:
        password = "TestPassword123!"
        email = f"chat_{uuid.uuid4().hex[:8]}@example.com"
        token = await _register_and_onboard(client, email, password, "Jordan")
        headers = {"Authorization": f"Bearer {token}"}

        created = await client.post("/api/v1/conversations", headers=headers, json={})
        assert created.status_code == 201
        conversation_id = created.json()["id"]
        assert created.json()["title"] == "New conversation"

        listed = await client.get("/api/v1/conversations", headers=headers)
        assert listed.status_code == 200
        assert len(listed.json()) == 1
        assert listed.json()[0]["id"] == conversation_id

        detail = await client.get(f"/api/v1/conversations/{conversation_id}", headers=headers)
        assert detail.status_code == 200
        assert detail.json()["messages"] == []

        empty_msg = await client.post(
            f"/api/v1/conversations/{conversation_id}/messages",
            headers=headers,
            json={"content": "   "},
        )
        assert empty_msg.status_code == 422

        sent = await client.post(
            f"/api/v1/conversations/{conversation_id}/messages",
            headers=headers,
            json={"content": "How can I wind down tonight?"},
        )
        assert sent.status_code == 201
        body = sent.json()
        assert body["user_message"]["role"] == "user"
        assert body["user_message"]["content"] == "How can I wind down tonight?"
        assert body["assistant_message"]["role"] == "assistant"
        assert body["assistant_message"]["content"] == fake_ai.reply
        assert fake_ai.calls == 1

        persisted = await client.get(
            f"/api/v1/conversations/{conversation_id}",
            headers=headers,
        )
        assert persisted.status_code == 200
        messages = persisted.json()["messages"]
        assert len(messages) == 2
        assert messages[0]["role"] == "user"
        assert messages[1]["role"] == "assistant"
        assert persisted.json()["title"] == "How can I wind down tonight?"


@pytest.mark.asyncio
async def test_conversation_isolation_between_users(fake_ai):
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as client:
        password = "TestPassword123!"
        token_a = await _register_and_onboard(
            client, f"a_{uuid.uuid4().hex[:8]}@example.com", password, "User A"
        )
        token_b = await _register_and_onboard(
            client, f"b_{uuid.uuid4().hex[:8]}@example.com", password, "User B"
        )
        headers_a = {"Authorization": f"Bearer {token_a}"}
        headers_b = {"Authorization": f"Bearer {token_b}"}

        created = await client.post("/api/v1/conversations", headers=headers_a, json={})
        conversation_id = created.json()["id"]
        await client.post(
            f"/api/v1/conversations/{conversation_id}/messages",
            headers=headers_a,
            json={"content": "Private note for user A"},
        )

        other_get = await client.get(
            f"/api/v1/conversations/{conversation_id}",
            headers=headers_b,
        )
        assert other_get.status_code == 404

        other_message = await client.post(
            f"/api/v1/conversations/{conversation_id}/messages",
            headers=headers_b,
            json={"content": "Trying to inject into A's conversation"},
        )
        assert other_message.status_code == 404

        other_delete = await client.delete(
            f"/api/v1/conversations/{conversation_id}",
            headers=headers_b,
        )
        assert other_delete.status_code == 404

        list_b = await client.get("/api/v1/conversations", headers=headers_b)
        assert list_b.status_code == 200
        assert list_b.json() == []


@pytest.mark.asyncio
async def test_ai_failure_does_not_persist_assistant_message(fake_ai):
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as client:
        token = await _register_and_onboard(
            client,
            f"ai_fail_{uuid.uuid4().hex[:8]}@example.com",
            "TestPassword123!",
            "Kai",
        )
        headers = {"Authorization": f"Bearer {token}"}
        created = await client.post("/api/v1/conversations", headers=headers, json={})
        conversation_id = created.json()["id"]

        fake_ai.fail_next = True
        failed = await client.post(
            f"/api/v1/conversations/{conversation_id}/messages",
            headers=headers,
            json={"content": "This should not produce an assistant row"},
        )
        assert failed.status_code == 502

        detail = await client.get(
            f"/api/v1/conversations/{conversation_id}",
            headers=headers,
        )
        messages = detail.json()["messages"]
        assert len(messages) == 1
        assert messages[0]["role"] == "user"
        assert all(item["role"] != "assistant" for item in messages)
